#!/usr/bin/bash
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/0-main.c 0-binary_tree_node.c -o 0-node
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/1-main.c 1-binary_tree_insert_left.c 0-binary_tree_node.c -o 1-left
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/2-main.c 2-binary_tree_insert_right.c 0-binary_tree_node.c -o 2-right
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/3-main.c 3-binary_tree_delete.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 3-del
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 4-binary_tree_is_leaf.c main/4-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 4-leaf
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 5-binary_tree_is_root.c main/5-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 5-root
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/6-main.c 6-binary_tree_preorder.c 0-binary_tree_node.c -o 6-pre
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/7-main.c 7-binary_tree_inorder.c 0-binary_tree_node.c -o 7-in
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/8-main.c 8-binary_tree_postorder.c 0-binary_tree_node.c -o 8-post
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 9-binary_tree_height.c main/9-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 9-height
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 10-binary_tree_depth.c main/10-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 10-depth
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 11-binary_tree_size.c main/11-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 11-size
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 12-binary_tree_leaves.c main/12-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 12-leaves
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 13-binary_tree_nodes.c main/13-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 13-nodes
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 14-binary_tree_balance.c main/14-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c 1-binary_tree_insert_left.c -o 14-balance
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 15-binary_tree_is_full.c main/15-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 15-full
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c 16-binary_tree_is_perfect.c main/16-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 16-perfect
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/17-main.c 17-binary_tree_sibling.c 0-binary_tree_node.c -o 17-sibling
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/18-main.c 18-binary_tree_uncle.c 0-binary_tree_node.c -o 18-uncle
gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/100-main.c 100-binary_trees_ancestor.c 0-binary_tree_node.c -o 100-ancestor

gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/101-main.c 101-binary_tree_levelorder.c 0-binary_tree_node.c 3-binary_tree_delete.c -o 101-lvl; valgrind ./101-lvl

gcc -Wall -Wextra -Werror -pedantic binary_tree_print.c main/102-main.c 102-binary_tree_is_complete.c 0-binary_tree_node.c 3-binary_tree_delete.c -o 102-complete

# history | grep "gcc.*main/" | tr -s ' ' | cut -d ' ' -f 3- | uniq > compilation
